apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-secret
  namespace: kt
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=