apiVersion: v1
kind: Service
metadata:
  name: resource-app
  namespace: kt
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30001
  selector:
    app: resource-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-app
  namespace: kt
  labels:
    app: resource-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-app
  template:
    metadata:
      namespace: kt
      labels:
        app: resource-app
    spec:
      containers:
        - name: resource-app
          image: resource-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: resource-service
            - name: SERVER_PORT
              value: '8080'
            - name: SONG_SERVICE_URL
              value: http://song-app:8082/songs/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://resource-db:5433/resource-db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: org.postgresql.Driver
            - name: SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE
              value: 100MB
            - name: SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE
              value: 100MB