apiVersion: v1
kind: Service
metadata:
  name: song-app
  namespace: kt
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30002
  selector:
    app: song-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-app
  namespace: kt
  labels:
    app: song-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-app
  template:
    metadata:
      namespace: kt
      labels:
        app: song-app
    spec:
      containers:
        - name: song-app
          image: song-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: song-app-config