apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: kt
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8082
      nodePort: 30002
  selector:
    app: song-service-app