apiVersion: v1
kind: Service
metadata:
  name: song-app
  namespace: kt
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30002
  selector:
    app: song-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-app
  namespace: kt
  labels:
    app: song-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-app
  template:
    metadata:
      namespace: kt
      labels:
        app: song-app
    spec:
      containers:
        - name: song-app
          image: song-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: song-service
            - name: SERVER_PORT
              value: '8080'
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://song-db:5434/song-db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: org.postgresql.Driver