apiVersion: v1
kind: Service
metadata:
  name: song-db
  namespace: kt
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5434
      targetPort: 5432
  selector:
    app: song-db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: song-db
  namespace: kt
spec:
  serviceName: "song-db"
  selector:
    matchLabels:
      app: song-db
  template:
    metadata:
      namespace: kt
      labels:
        app: song-db
    spec:
      containers:
        - name: song-db
          image: song-db:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: song-db
          volumeMounts:
            - name: song-db-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: song-db-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi