apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: kt.io
      http:
        paths:
          - path: /resource-app/api/v1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: resource-app
                port:
                  number: 8081
    - host: kt.io
      http:
        paths:
          - path: /song-app/api/v1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: song-app
                port:
                  number: 8082