apiVersion: v1
kind: Service
metadata:
  name: resource-app
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  selector:
    app: resource-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-app
  namespace: {{ .Values.namespace }}
  labels:
    app: resource-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: resource-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: resource-app
    spec:
      containers:
        - name: resource-app
          image: resource-service:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: resource-app-config
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
